### ISSUE TITLE
Profile Bug

### ISSUE THREAD

**Issue by chuuloona** [NoxCaos/amusementclub2.0#14]
When trying to command **->profile**

Issue:
**user.js:253:34**
**const stampString = `${stamp.getFullYear()}.${(stamp.getMonth()+1)}.${stamp.getDate()}`**

```
TypeError: Cannot read property 'getFullYear' of undefined
    at Object.<anonymous> (C:\Users\Seulgi\Desktop\amusementclub\amusementClub2.0\commands\user.js:253:34)
    at trigger (C:\Users\Seulgi\Desktop\amusementclub\amusementClub2.0\utils\cmd.js:83:39)
    at Client.<anonymous> (C:\Users\Seulgi\Desktop\amusementclub\amusementClub2.0\index.js:201:19)        
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[ERR] TypeError: Cannot read property 'getFullYear' of undefined
    at Object.<anonymous> (C:\Users\Seulgi\Desktop\amusementclub\amusementClub2.0\commands\user.js:253:34)
    at trigger (C:\Users\Seulgi\Desktop\amusementclub\amusementClub2.0\utils\cmd.js:83:39)
    at Client.<anonymous> (C:\Users\Seulgi\Desktop\amusementclub\amusementClub2.0\index.js:201:19)        
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by NoxCaos** [comment]
Fixed in 29b2de58dbb5486aa106032a4385a3bd3d294990
