### ISSUE TITLE
TypeError: Cannot read property 'compressed' of undefined [index.js]

### ISSUE THREAD

**Issue by chuuloona** [NoxCaos/amusementclub2.0#15]
```
[ERR] TypeError: Cannot read property 'compressed' of undefined
    at C:\Users\Seulgi\Desktop\amusementclub\amusementClub2.0\index.js:37:50
    at Array.map (<anonymous>)
    at fillCardData (C:\Users\Seulgi\Desktop\amusementclub\amusementClub2.0\index.js:35:31)
    at Object.module.exports.create (C:\Users\Seulgi\Desktop\amusementclub\amusementClub2.0\index.js:47:5)
    at create (C:\Users\Seulgi\Desktop\amusementclub\ayano\modules\amusement.js:23:32)
    at startBot (C:\Users\Seulgi\Desktop\amusementclub\ayano\modules\amusement.js:37:25)
    at C:\Users\Seulgi\Desktop\amusementclub\ayano\core\with.js:41:12
    at C:\Users\Seulgi\Desktop\amusementclub\ayano\core\with.js:17:12
    at Object.<anonymous> (C:\Users\Seulgi\Desktop\amusementclub\ayano\core\with.js:86:12)
    at trigger (C:\Users\Seulgi\Desktop\amusementclub\ayano\core\cmd.js:41:29)
    at Object.input (C:\Users\Seulgi\Desktop\amusementclub\ayano\core\index.js:28:19)
    at Interface.<anonymous> (C:\Users\Seulgi\Desktop\amusementclub\ayano\modules\cli.js:21:19)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._line (readline.js:658:8)
    at Interface._ttyWrite (readline.js:999:14)

```

line 35:31 index.js
**const ext = x.animated? 'gif' : (col.compressed? 'jpg' : 'png')**

**Comment by NoxCaos** [comment]
This is related to you having a card from collection that doesn't exist. This but should not appear if you add cards correctly using Ayano's S3 utility

**Comment by chuuloona** [comment]
i have a dedicated promo folder, i have a promo collection also.

folder name in spaces = **promo**
collection name =` {"id": "promo","name": "NIZI U","aliases": ["promo","niziu"],"promo": true,"compressed": true},`

updated using ayano.

example of 1 card from promo

```
{
    "name": "niziu_ayaka",
    "level": 1,
    "animated": false,
    "col": "promo"
  },
```

**Comment by NoxCaos** [comment]
The issue is still in your data. As I said before 'This is related to you having a card from collection that doesn't exist.'
I cannot help you since I don't know how you got the corrupted data in your JSON

**Comment by chuuloona** [comment]
thanks! i'll look into it.
